# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Swift-Demo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  #pod 'BJNumberPlateSwift'

  # Pods for Swift-Demo

  target 'Swift-DemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Swift-DemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
