# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OC-Demo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'BJNumberPlateOC'

  # Pods for OC-Demo

  target 'OC-DemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OC-DemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
